/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as SettingsTaxesRouteImport } from './routes/settings.taxes'
import { Route as SettingsSalesRepsRouteImport } from './routes/settings.sales-reps'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'
import { Route as SalesInvoicesRouteImport } from './routes/sales.invoices'
import { Route as SalesCustomersRouteImport } from './routes/sales.customers'
import { Route as SalesCreditNotesRouteImport } from './routes/sales.credit-notes'
import { Route as ReportsSalesReportRouteImport } from './routes/reports.sales-report'
import { Route as PurchasesSuppliersRouteImport } from './routes/purchases.suppliers'
import { Route as PurchasesPurchaseOrdersRouteImport } from './routes/purchases.purchase-orders'
import { Route as PurchasesBillsRouteImport } from './routes/purchases.bills'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryReportsRouteImport } from './routes/inventory.reports'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as InventoryAdjustmentsRouteImport } from './routes/inventory.adjustments'
import { Route as CashTransfersRouteImport } from './routes/cash.transfers'
import { Route as CashTransactionsRouteImport } from './routes/cash.transactions'
import { Route as CashReceiptsRouteImport } from './routes/cash.receipts'
import { Route as CashPaymentsRouteImport } from './routes/cash.payments'
import { Route as CashBanksRouteImport } from './routes/cash.banks'
import { Route as SalesQuotationsIndexRouteImport } from './routes/sales.quotations.index'
import { Route as SalesInvoicesIndexRouteImport } from './routes/sales.invoices.index'
import { Route as SalesCreditNotesIndexRouteImport } from './routes/sales.credit-notes.index'
import { Route as PurchasesPurchaseOrdersIndexRouteImport } from './routes/purchases.purchase-orders.index'
import { Route as PurchasesBillsIndexRouteImport } from './routes/purchases.bills.index'
import { Route as SalesQuotationsNewRouteImport } from './routes/sales.quotations.new'
import { Route as SalesQuotationsIdRouteImport } from './routes/sales.quotations.$id'
import { Route as SalesInvoicesNewRouteImport } from './routes/sales.invoices.new'
import { Route as SalesInvoicesIdRouteImport } from './routes/sales.invoices.$id'
import { Route as SalesCreditNotesNewRouteImport } from './routes/sales.credit-notes.new'
import { Route as SalesCreditNotesIdRouteImport } from './routes/sales.credit-notes.$id'
import { Route as PurchasesPurchaseOrdersNewRouteImport } from './routes/purchases.purchase-orders.new'
import { Route as PurchasesPurchaseOrdersIdRouteImport } from './routes/purchases.purchase-orders.$id'
import { Route as PurchasesBillsNewRouteImport } from './routes/purchases.bills.new'
import { Route as PurchasesBillsIdRouteImport } from './routes/purchases.bills.$id'

const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/settings/templates',
  path: '/settings/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTaxesRoute = SettingsTaxesRouteImport.update({
  id: '/settings/taxes',
  path: '/settings/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesRepsRoute = SettingsSalesRepsRouteImport.update({
  id: '/settings/sales-reps',
  path: '/settings/sales-reps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCreditNotesRoute = SalesCreditNotesRouteImport.update({
  id: '/sales/credit-notes',
  path: '/sales/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesReportRoute = ReportsSalesReportRouteImport.update({
  id: '/reports/sales-report',
  path: '/reports/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesSuppliersRoute = PurchasesSuppliersRouteImport.update({
  id: '/purchases/suppliers',
  path: '/purchases/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPurchaseOrdersRoute = PurchasesPurchaseOrdersRouteImport.update({
  id: '/purchases/purchase-orders',
  path: '/purchases/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesBillsRoute = PurchasesBillsRouteImport.update({
  id: '/purchases/bills',
  path: '/purchases/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryReportsRoute = InventoryReportsRouteImport.update({
  id: '/inventory/reports',
  path: '/inventory/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentsRoute = InventoryAdjustmentsRouteImport.update({
  id: '/inventory/adjustments',
  path: '/inventory/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const CashTransfersRoute = CashTransfersRouteImport.update({
  id: '/cash/transfers',
  path: '/cash/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashTransactionsRoute = CashTransactionsRouteImport.update({
  id: '/cash/transactions',
  path: '/cash/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CashReceiptsRoute = CashReceiptsRouteImport.update({
  id: '/cash/receipts',
  path: '/cash/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const CashPaymentsRoute = CashPaymentsRouteImport.update({
  id: '/cash/payments',
  path: '/cash/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBanksRoute = CashBanksRouteImport.update({
  id: '/cash/banks',
  path: '/cash/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsIndexRoute = SalesQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesInvoicesIndexRoute = SalesInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesCreditNotesIndexRoute = SalesCreditNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const PurchasesPurchaseOrdersIndexRoute =
  PurchasesPurchaseOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesBillsIndexRoute = PurchasesBillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasesBillsRoute,
} as any)
const SalesQuotationsNewRoute = SalesQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesQuotationsIdRoute = SalesQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesInvoicesNewRoute = SalesInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesInvoicesIdRoute = SalesInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesCreditNotesNewRoute = SalesCreditNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const SalesCreditNotesIdRoute = SalesCreditNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const PurchasesPurchaseOrdersNewRoute =
  PurchasesPurchaseOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesPurchaseOrdersIdRoute =
  PurchasesPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesBillsNewRoute = PurchasesBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesBillsRoute,
} as any)
const PurchasesBillsIdRoute = PurchasesBillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchasesBillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/bills': typeof PurchasesBillsRouteWithChildren
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRouteWithChildren
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/sales/credit-notes': typeof SalesCreditNotesRouteWithChildren
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/sales/quotations': typeof SalesQuotationsRouteWithChildren
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills/': typeof PurchasesBillsIndexRoute
  '/purchases/purchase-orders/': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes/': typeof SalesCreditNotesIndexRoute
  '/sales/invoices/': typeof SalesInvoicesIndexRoute
  '/sales/quotations/': typeof SalesQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills': typeof PurchasesBillsIndexRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes': typeof SalesCreditNotesIndexRoute
  '/sales/invoices': typeof SalesInvoicesIndexRoute
  '/sales/quotations': typeof SalesQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/bills': typeof PurchasesBillsRouteWithChildren
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRouteWithChildren
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/sales/credit-notes': typeof SalesCreditNotesRouteWithChildren
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/sales/quotations': typeof SalesQuotationsRouteWithChildren
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills/': typeof PurchasesBillsIndexRoute
  '/purchases/purchase-orders/': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes/': typeof SalesCreditNotesIndexRoute
  '/sales/invoices/': typeof SalesInvoicesIndexRoute
  '/sales/quotations/': typeof SalesQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/auth'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/bills'
    | '/purchases/purchase-orders'
    | '/purchases/suppliers'
    | '/reports/sales-report'
    | '/sales/credit-notes'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/quotations'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/users'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills/'
    | '/purchases/purchase-orders/'
    | '/sales/credit-notes/'
    | '/sales/invoices/'
    | '/sales/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/auth'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/suppliers'
    | '/reports/sales-report'
    | '/sales/customers'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/users'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills'
    | '/purchases/purchase-orders'
    | '/sales/credit-notes'
    | '/sales/invoices'
    | '/sales/quotations'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/auth'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/bills'
    | '/purchases/purchase-orders'
    | '/purchases/suppliers'
    | '/reports/sales-report'
    | '/sales/credit-notes'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/quotations'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/users'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills/'
    | '/purchases/purchase-orders/'
    | '/sales/credit-notes/'
    | '/sales/invoices/'
    | '/sales/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  CashBanksRoute: typeof CashBanksRoute
  CashPaymentsRoute: typeof CashPaymentsRoute
  CashReceiptsRoute: typeof CashReceiptsRoute
  CashTransactionsRoute: typeof CashTransactionsRoute
  CashTransfersRoute: typeof CashTransfersRoute
  InventoryAdjustmentsRoute: typeof InventoryAdjustmentsRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryReportsRoute: typeof InventoryReportsRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  PurchasesBillsRoute: typeof PurchasesBillsRouteWithChildren
  PurchasesPurchaseOrdersRoute: typeof PurchasesPurchaseOrdersRouteWithChildren
  PurchasesSuppliersRoute: typeof PurchasesSuppliersRoute
  ReportsSalesReportRoute: typeof ReportsSalesReportRoute
  SalesCreditNotesRoute: typeof SalesCreditNotesRouteWithChildren
  SalesCustomersRoute: typeof SalesCustomersRoute
  SalesInvoicesRoute: typeof SalesInvoicesRouteWithChildren
  SalesQuotationsRoute: typeof SalesQuotationsRouteWithChildren
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSalesRepsRoute: typeof SettingsSalesRepsRoute
  SettingsTaxesRoute: typeof SettingsTaxesRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/taxes': {
      id: '/settings/taxes'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof SettingsTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales-reps': {
      id: '/settings/sales-reps'
      path: '/settings/sales-reps'
      fullPath: '/settings/sales-reps'
      preLoaderRoute: typeof SettingsSalesRepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices': {
      id: '/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/credit-notes': {
      id: '/sales/credit-notes'
      path: '/sales/credit-notes'
      fullPath: '/sales/credit-notes'
      preLoaderRoute: typeof SalesCreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales-report': {
      id: '/reports/sales-report'
      path: '/reports/sales-report'
      fullPath: '/reports/sales-report'
      preLoaderRoute: typeof ReportsSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/suppliers': {
      id: '/purchases/suppliers'
      path: '/purchases/suppliers'
      fullPath: '/purchases/suppliers'
      preLoaderRoute: typeof PurchasesSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/purchase-orders': {
      id: '/purchases/purchase-orders'
      path: '/purchases/purchase-orders'
      fullPath: '/purchases/purchase-orders'
      preLoaderRoute: typeof PurchasesPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/bills': {
      id: '/purchases/bills'
      path: '/purchases/bills'
      fullPath: '/purchases/bills'
      preLoaderRoute: typeof PurchasesBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/reports': {
      id: '/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof InventoryReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/adjustments': {
      id: '/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof InventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/transfers': {
      id: '/cash/transfers'
      path: '/cash/transfers'
      fullPath: '/cash/transfers'
      preLoaderRoute: typeof CashTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/transactions': {
      id: '/cash/transactions'
      path: '/cash/transactions'
      fullPath: '/cash/transactions'
      preLoaderRoute: typeof CashTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/receipts': {
      id: '/cash/receipts'
      path: '/cash/receipts'
      fullPath: '/cash/receipts'
      preLoaderRoute: typeof CashReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/payments': {
      id: '/cash/payments'
      path: '/cash/payments'
      fullPath: '/cash/payments'
      preLoaderRoute: typeof CashPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/banks': {
      id: '/cash/banks'
      path: '/cash/banks'
      fullPath: '/cash/banks'
      preLoaderRoute: typeof CashBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations/': {
      id: '/sales/quotations/'
      path: '/'
      fullPath: '/sales/quotations/'
      preLoaderRoute: typeof SalesQuotationsIndexRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/invoices/': {
      id: '/sales/invoices/'
      path: '/'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof SalesInvoicesIndexRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/credit-notes/': {
      id: '/sales/credit-notes/'
      path: '/'
      fullPath: '/sales/credit-notes/'
      preLoaderRoute: typeof SalesCreditNotesIndexRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/purchases/purchase-orders/': {
      id: '/purchases/purchase-orders/'
      path: '/'
      fullPath: '/purchases/purchase-orders/'
      preLoaderRoute: typeof PurchasesPurchaseOrdersIndexRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/bills/': {
      id: '/purchases/bills/'
      path: '/'
      fullPath: '/purchases/bills/'
      preLoaderRoute: typeof PurchasesBillsIndexRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
    '/sales/quotations/new': {
      id: '/sales/quotations/new'
      path: '/new'
      fullPath: '/sales/quotations/new'
      preLoaderRoute: typeof SalesQuotationsNewRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/quotations/$id': {
      id: '/sales/quotations/$id'
      path: '/$id'
      fullPath: '/sales/quotations/$id'
      preLoaderRoute: typeof SalesQuotationsIdRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/invoices/new': {
      id: '/sales/invoices/new'
      path: '/new'
      fullPath: '/sales/invoices/new'
      preLoaderRoute: typeof SalesInvoicesNewRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/invoices/$id': {
      id: '/sales/invoices/$id'
      path: '/$id'
      fullPath: '/sales/invoices/$id'
      preLoaderRoute: typeof SalesInvoicesIdRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/credit-notes/new': {
      id: '/sales/credit-notes/new'
      path: '/new'
      fullPath: '/sales/credit-notes/new'
      preLoaderRoute: typeof SalesCreditNotesNewRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/sales/credit-notes/$id': {
      id: '/sales/credit-notes/$id'
      path: '/$id'
      fullPath: '/sales/credit-notes/$id'
      preLoaderRoute: typeof SalesCreditNotesIdRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/purchases/purchase-orders/new': {
      id: '/purchases/purchase-orders/new'
      path: '/new'
      fullPath: '/purchases/purchase-orders/new'
      preLoaderRoute: typeof PurchasesPurchaseOrdersNewRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/purchase-orders/$id': {
      id: '/purchases/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchases/purchase-orders/$id'
      preLoaderRoute: typeof PurchasesPurchaseOrdersIdRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/bills/new': {
      id: '/purchases/bills/new'
      path: '/new'
      fullPath: '/purchases/bills/new'
      preLoaderRoute: typeof PurchasesBillsNewRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
    '/purchases/bills/$id': {
      id: '/purchases/bills/$id'
      path: '/$id'
      fullPath: '/purchases/bills/$id'
      preLoaderRoute: typeof PurchasesBillsIdRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
  }
}

interface PurchasesBillsRouteChildren {
  PurchasesBillsIdRoute: typeof PurchasesBillsIdRoute
  PurchasesBillsNewRoute: typeof PurchasesBillsNewRoute
  PurchasesBillsIndexRoute: typeof PurchasesBillsIndexRoute
}

const PurchasesBillsRouteChildren: PurchasesBillsRouteChildren = {
  PurchasesBillsIdRoute: PurchasesBillsIdRoute,
  PurchasesBillsNewRoute: PurchasesBillsNewRoute,
  PurchasesBillsIndexRoute: PurchasesBillsIndexRoute,
}

const PurchasesBillsRouteWithChildren = PurchasesBillsRoute._addFileChildren(
  PurchasesBillsRouteChildren,
)

interface PurchasesPurchaseOrdersRouteChildren {
  PurchasesPurchaseOrdersIdRoute: typeof PurchasesPurchaseOrdersIdRoute
  PurchasesPurchaseOrdersNewRoute: typeof PurchasesPurchaseOrdersNewRoute
  PurchasesPurchaseOrdersIndexRoute: typeof PurchasesPurchaseOrdersIndexRoute
}

const PurchasesPurchaseOrdersRouteChildren: PurchasesPurchaseOrdersRouteChildren =
  {
    PurchasesPurchaseOrdersIdRoute: PurchasesPurchaseOrdersIdRoute,
    PurchasesPurchaseOrdersNewRoute: PurchasesPurchaseOrdersNewRoute,
    PurchasesPurchaseOrdersIndexRoute: PurchasesPurchaseOrdersIndexRoute,
  }

const PurchasesPurchaseOrdersRouteWithChildren =
  PurchasesPurchaseOrdersRoute._addFileChildren(
    PurchasesPurchaseOrdersRouteChildren,
  )

interface SalesCreditNotesRouteChildren {
  SalesCreditNotesIdRoute: typeof SalesCreditNotesIdRoute
  SalesCreditNotesNewRoute: typeof SalesCreditNotesNewRoute
  SalesCreditNotesIndexRoute: typeof SalesCreditNotesIndexRoute
}

const SalesCreditNotesRouteChildren: SalesCreditNotesRouteChildren = {
  SalesCreditNotesIdRoute: SalesCreditNotesIdRoute,
  SalesCreditNotesNewRoute: SalesCreditNotesNewRoute,
  SalesCreditNotesIndexRoute: SalesCreditNotesIndexRoute,
}

const SalesCreditNotesRouteWithChildren =
  SalesCreditNotesRoute._addFileChildren(SalesCreditNotesRouteChildren)

interface SalesInvoicesRouteChildren {
  SalesInvoicesIdRoute: typeof SalesInvoicesIdRoute
  SalesInvoicesNewRoute: typeof SalesInvoicesNewRoute
  SalesInvoicesIndexRoute: typeof SalesInvoicesIndexRoute
}

const SalesInvoicesRouteChildren: SalesInvoicesRouteChildren = {
  SalesInvoicesIdRoute: SalesInvoicesIdRoute,
  SalesInvoicesNewRoute: SalesInvoicesNewRoute,
  SalesInvoicesIndexRoute: SalesInvoicesIndexRoute,
}

const SalesInvoicesRouteWithChildren = SalesInvoicesRoute._addFileChildren(
  SalesInvoicesRouteChildren,
)

interface SalesQuotationsRouteChildren {
  SalesQuotationsIdRoute: typeof SalesQuotationsIdRoute
  SalesQuotationsNewRoute: typeof SalesQuotationsNewRoute
  SalesQuotationsIndexRoute: typeof SalesQuotationsIndexRoute
}

const SalesQuotationsRouteChildren: SalesQuotationsRouteChildren = {
  SalesQuotationsIdRoute: SalesQuotationsIdRoute,
  SalesQuotationsNewRoute: SalesQuotationsNewRoute,
  SalesQuotationsIndexRoute: SalesQuotationsIndexRoute,
}

const SalesQuotationsRouteWithChildren = SalesQuotationsRoute._addFileChildren(
  SalesQuotationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  CashBanksRoute: CashBanksRoute,
  CashPaymentsRoute: CashPaymentsRoute,
  CashReceiptsRoute: CashReceiptsRoute,
  CashTransactionsRoute: CashTransactionsRoute,
  CashTransfersRoute: CashTransfersRoute,
  InventoryAdjustmentsRoute: InventoryAdjustmentsRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryReportsRoute: InventoryReportsRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  PurchasesBillsRoute: PurchasesBillsRouteWithChildren,
  PurchasesPurchaseOrdersRoute: PurchasesPurchaseOrdersRouteWithChildren,
  PurchasesSuppliersRoute: PurchasesSuppliersRoute,
  ReportsSalesReportRoute: ReportsSalesReportRoute,
  SalesCreditNotesRoute: SalesCreditNotesRouteWithChildren,
  SalesCustomersRoute: SalesCustomersRoute,
  SalesInvoicesRoute: SalesInvoicesRouteWithChildren,
  SalesQuotationsRoute: SalesQuotationsRouteWithChildren,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSalesRepsRoute: SettingsSalesRepsRoute,
  SettingsTaxesRoute: SettingsTaxesRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
