/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWorkflowsRouteImport } from './routes/settings.workflows'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsTestDataRouteImport } from './routes/settings.test-data'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as SettingsTaxesRouteImport } from './routes/settings.taxes'
import { Route as SettingsSalesRepsRouteImport } from './routes/settings.sales-reps'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsPaymentMethodsRouteImport } from './routes/settings.payment-methods'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as SettingsNumberingRouteImport } from './routes/settings.numbering'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsImportExportRouteImport } from './routes/settings.import-export'
import { Route as SettingsFinanceHealthRouteImport } from './routes/settings.finance-health'
import { Route as SettingsDeterminationsRouteImport } from './routes/settings.determinations'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings.currencies'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAuditLogRouteImport } from './routes/settings.audit-log'
import { Route as SettingsApThresholdsRouteImport } from './routes/settings.ap-thresholds'
import { Route as SettingsAccountingFoundationRouteImport } from './routes/settings.accounting-foundation'
import { Route as SalesStatementsRouteImport } from './routes/sales.statements'
import { Route as SalesRecurringRouteImport } from './routes/sales.recurring'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'
import { Route as SalesInvoicesRouteImport } from './routes/sales.invoices'
import { Route as SalesCustomersRouteImport } from './routes/sales.customers'
import { Route as SalesCreditNotesRouteImport } from './routes/sales.credit-notes'
import { Route as ReportsVatReturnRouteImport } from './routes/reports.vat-return'
import { Route as ReportsTrialBalanceRouteImport } from './routes/reports.trial-balance'
import { Route as ReportsStatementRouteImport } from './routes/reports.statement'
import { Route as ReportsSalesReportRouteImport } from './routes/reports.sales-report'
import { Route as ReportsSalesByItemRouteImport } from './routes/reports.sales-by-item'
import { Route as ReportsSalesByCustomerRouteImport } from './routes/reports.sales-by-customer'
import { Route as ReportsPurchasesBySupplierRouteImport } from './routes/reports.purchases-by-supplier'
import { Route as ReportsProfitAndLossRouteImport } from './routes/reports.profit-and-loss'
import { Route as ReportsBalanceSheetRouteImport } from './routes/reports.balance-sheet'
import { Route as ReportsAgedReceivablesRouteImport } from './routes/reports.aged-receivables'
import { Route as ReportsAgedPayablesRouteImport } from './routes/reports.aged-payables'
import { Route as PurchasesSuppliersRouteImport } from './routes/purchases.suppliers'
import { Route as PurchasesScanRouteImport } from './routes/purchases.scan'
import { Route as PurchasesPurchaseOrdersRouteImport } from './routes/purchases.purchase-orders'
import { Route as PurchasesInboxRouteImport } from './routes/purchases.inbox'
import { Route as PurchasesDebitNotesRouteImport } from './routes/purchases.debit-notes'
import { Route as PurchasesBillsRouteImport } from './routes/purchases.bills'
import { Route as PurchasesApReviewRouteImport } from './routes/purchases.ap-review'
import { Route as PurchasesApDashboardRouteImport } from './routes/purchases.ap-dashboard'
import { Route as PurchasesApCopilotRouteImport } from './routes/purchases.ap-copilot'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryReportsRouteImport } from './routes/inventory.reports'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as InventoryAdjustmentsRouteImport } from './routes/inventory.adjustments'
import { Route as InboxUploadTokenRouteImport } from './routes/inbox-upload.$token'
import { Route as DashboardProfitAndLossRouteImport } from './routes/dashboard.profit-and-loss'
import { Route as DashboardCashFlowRouteImport } from './routes/dashboard.cash-flow'
import { Route as CashTransfersRouteImport } from './routes/cash.transfers'
import { Route as CashTransactionsRouteImport } from './routes/cash.transactions'
import { Route as CashReconciliationRouteImport } from './routes/cash.reconciliation'
import { Route as CashReceiptsRouteImport } from './routes/cash.receipts'
import { Route as CashPaymentsRouteImport } from './routes/cash.payments'
import { Route as CashBanksRouteImport } from './routes/cash.banks'
import { Route as AccountingJournalEntriesRouteImport } from './routes/accounting.journal-entries'
import { Route as AccountingGeneralLedgerRouteImport } from './routes/accounting.general-ledger'
import { Route as AccountingChartOfAccountsRouteImport } from './routes/accounting.chart-of-accounts'
import { Route as SalesQuotationsIndexRouteImport } from './routes/sales.quotations.index'
import { Route as SalesInvoicesIndexRouteImport } from './routes/sales.invoices.index'
import { Route as SalesCreditNotesIndexRouteImport } from './routes/sales.credit-notes.index'
import { Route as PurchasesPurchaseOrdersIndexRouteImport } from './routes/purchases.purchase-orders.index'
import { Route as PurchasesDebitNotesIndexRouteImport } from './routes/purchases.debit-notes.index'
import { Route as PurchasesBillsIndexRouteImport } from './routes/purchases.bills.index'
import { Route as SalesQuotationsNewRouteImport } from './routes/sales.quotations.new'
import { Route as SalesQuotationsIdRouteImport } from './routes/sales.quotations.$id'
import { Route as SalesInvoicesNewRouteImport } from './routes/sales.invoices.new'
import { Route as SalesInvoicesIdRouteImport } from './routes/sales.invoices.$id'
import { Route as SalesCreditNotesNewRouteImport } from './routes/sales.credit-notes.new'
import { Route as SalesCreditNotesIdRouteImport } from './routes/sales.credit-notes.$id'
import { Route as PurchasesPurchaseOrdersNewRouteImport } from './routes/purchases.purchase-orders.new'
import { Route as PurchasesPurchaseOrdersIdRouteImport } from './routes/purchases.purchase-orders.$id'
import { Route as PurchasesDebitNotesNewRouteImport } from './routes/purchases.debit-notes.new'
import { Route as PurchasesDebitNotesIdRouteImport } from './routes/purchases.debit-notes.$id'
import { Route as PurchasesBillsNewRouteImport } from './routes/purchases.bills.new'
import { Route as PurchasesBillsIdRouteImport } from './routes/purchases.bills.$id'
import { Route as ApiPublicHooksFinanceHealthRouteImport } from './routes/api/public/hooks/finance-health'
import { Route as ApiPublicHooksApIntakeWhatsappRouteImport } from './routes/api/public/hooks/ap-intake-whatsapp'
import { Route as ApiPublicHooksApIntakeProcessRouteImport } from './routes/api/public/hooks/ap-intake-process'
import { Route as ApiPublicHooksApIntakeEmailRouteImport } from './routes/api/public/hooks/ap-intake-email'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkflowsRoute = SettingsWorkflowsRouteImport.update({
  id: '/settings/workflows',
  path: '/settings/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTestDataRoute = SettingsTestDataRouteImport.update({
  id: '/settings/test-data',
  path: '/settings/test-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/settings/templates',
  path: '/settings/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTaxesRoute = SettingsTaxesRouteImport.update({
  id: '/settings/taxes',
  path: '/settings/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesRepsRoute = SettingsSalesRepsRouteImport.update({
  id: '/settings/sales-reps',
  path: '/settings/sales-reps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentMethodsRoute = SettingsPaymentMethodsRouteImport.update({
  id: '/settings/payment-methods',
  path: '/settings/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNumberingRoute = SettingsNumberingRouteImport.update({
  id: '/settings/numbering',
  path: '/settings/numbering',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsImportExportRoute = SettingsImportExportRouteImport.update({
  id: '/settings/import-export',
  path: '/settings/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFinanceHealthRoute = SettingsFinanceHealthRouteImport.update({
  id: '/settings/finance-health',
  path: '/settings/finance-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeterminationsRoute = SettingsDeterminationsRouteImport.update({
  id: '/settings/determinations',
  path: '/settings/determinations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/settings/currencies',
  path: '/settings/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApThresholdsRoute = SettingsApThresholdsRouteImport.update({
  id: '/settings/ap-thresholds',
  path: '/settings/ap-thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountingFoundationRoute =
  SettingsAccountingFoundationRouteImport.update({
    id: '/settings/accounting-foundation',
    path: '/settings/accounting-foundation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalesStatementsRoute = SalesStatementsRouteImport.update({
  id: '/sales/statements',
  path: '/sales/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRecurringRoute = SalesRecurringRouteImport.update({
  id: '/sales/recurring',
  path: '/sales/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCreditNotesRoute = SalesCreditNotesRouteImport.update({
  id: '/sales/credit-notes',
  path: '/sales/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVatReturnRoute = ReportsVatReturnRouteImport.update({
  id: '/reports/vat-return',
  path: '/reports/vat-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTrialBalanceRoute = ReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStatementRoute = ReportsStatementRouteImport.update({
  id: '/reports/statement',
  path: '/reports/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesReportRoute = ReportsSalesReportRouteImport.update({
  id: '/reports/sales-report',
  path: '/reports/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesByItemRoute = ReportsSalesByItemRouteImport.update({
  id: '/reports/sales-by-item',
  path: '/reports/sales-by-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesByCustomerRoute = ReportsSalesByCustomerRouteImport.update({
  id: '/reports/sales-by-customer',
  path: '/reports/sales-by-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPurchasesBySupplierRoute =
  ReportsPurchasesBySupplierRouteImport.update({
    id: '/reports/purchases-by-supplier',
    path: '/reports/purchases-by-supplier',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsProfitAndLossRoute = ReportsProfitAndLossRouteImport.update({
  id: '/reports/profit-and-loss',
  path: '/reports/profit-and-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBalanceSheetRoute = ReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAgedReceivablesRoute = ReportsAgedReceivablesRouteImport.update({
  id: '/reports/aged-receivables',
  path: '/reports/aged-receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAgedPayablesRoute = ReportsAgedPayablesRouteImport.update({
  id: '/reports/aged-payables',
  path: '/reports/aged-payables',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesSuppliersRoute = PurchasesSuppliersRouteImport.update({
  id: '/purchases/suppliers',
  path: '/purchases/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesScanRoute = PurchasesScanRouteImport.update({
  id: '/purchases/scan',
  path: '/purchases/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPurchaseOrdersRoute = PurchasesPurchaseOrdersRouteImport.update({
  id: '/purchases/purchase-orders',
  path: '/purchases/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesInboxRoute = PurchasesInboxRouteImport.update({
  id: '/purchases/inbox',
  path: '/purchases/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesDebitNotesRoute = PurchasesDebitNotesRouteImport.update({
  id: '/purchases/debit-notes',
  path: '/purchases/debit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesBillsRoute = PurchasesBillsRouteImport.update({
  id: '/purchases/bills',
  path: '/purchases/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesApReviewRoute = PurchasesApReviewRouteImport.update({
  id: '/purchases/ap-review',
  path: '/purchases/ap-review',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesApDashboardRoute = PurchasesApDashboardRouteImport.update({
  id: '/purchases/ap-dashboard',
  path: '/purchases/ap-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesApCopilotRoute = PurchasesApCopilotRouteImport.update({
  id: '/purchases/ap-copilot',
  path: '/purchases/ap-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryReportsRoute = InventoryReportsRouteImport.update({
  id: '/inventory/reports',
  path: '/inventory/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentsRoute = InventoryAdjustmentsRouteImport.update({
  id: '/inventory/adjustments',
  path: '/inventory/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxUploadTokenRoute = InboxUploadTokenRouteImport.update({
  id: '/inbox-upload/$token',
  path: '/inbox-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfitAndLossRoute = DashboardProfitAndLossRouteImport.update({
  id: '/profit-and-loss',
  path: '/profit-and-loss',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCashFlowRoute = DashboardCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => DashboardRoute,
} as any)
const CashTransfersRoute = CashTransfersRouteImport.update({
  id: '/cash/transfers',
  path: '/cash/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashTransactionsRoute = CashTransactionsRouteImport.update({
  id: '/cash/transactions',
  path: '/cash/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CashReconciliationRoute = CashReconciliationRouteImport.update({
  id: '/cash/reconciliation',
  path: '/cash/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const CashReceiptsRoute = CashReceiptsRouteImport.update({
  id: '/cash/receipts',
  path: '/cash/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const CashPaymentsRoute = CashPaymentsRouteImport.update({
  id: '/cash/payments',
  path: '/cash/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBanksRoute = CashBanksRouteImport.update({
  id: '/cash/banks',
  path: '/cash/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingJournalEntriesRoute =
  AccountingJournalEntriesRouteImport.update({
    id: '/journal-entries',
    path: '/journal-entries',
    getParentRoute: () => AccountingRoute,
  } as any)
const AccountingGeneralLedgerRoute = AccountingGeneralLedgerRouteImport.update({
  id: '/general-ledger',
  path: '/general-ledger',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingChartOfAccountsRoute =
  AccountingChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AccountingRoute,
  } as any)
const SalesQuotationsIndexRoute = SalesQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesInvoicesIndexRoute = SalesInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesCreditNotesIndexRoute = SalesCreditNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const PurchasesPurchaseOrdersIndexRoute =
  PurchasesPurchaseOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesDebitNotesIndexRoute =
  PurchasesDebitNotesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PurchasesDebitNotesRoute,
  } as any)
const PurchasesBillsIndexRoute = PurchasesBillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasesBillsRoute,
} as any)
const SalesQuotationsNewRoute = SalesQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesQuotationsIdRoute = SalesQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesQuotationsRoute,
} as any)
const SalesInvoicesNewRoute = SalesInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesInvoicesIdRoute = SalesInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesInvoicesRoute,
} as any)
const SalesCreditNotesNewRoute = SalesCreditNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const SalesCreditNotesIdRoute = SalesCreditNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesCreditNotesRoute,
} as any)
const PurchasesPurchaseOrdersNewRoute =
  PurchasesPurchaseOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesPurchaseOrdersIdRoute =
  PurchasesPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PurchasesPurchaseOrdersRoute,
  } as any)
const PurchasesDebitNotesNewRoute = PurchasesDebitNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesDebitNotesRoute,
} as any)
const PurchasesDebitNotesIdRoute = PurchasesDebitNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchasesDebitNotesRoute,
} as any)
const PurchasesBillsNewRoute = PurchasesBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesBillsRoute,
} as any)
const PurchasesBillsIdRoute = PurchasesBillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchasesBillsRoute,
} as any)
const ApiPublicHooksFinanceHealthRoute =
  ApiPublicHooksFinanceHealthRouteImport.update({
    id: '/api/public/hooks/finance-health',
    path: '/api/public/hooks/finance-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApIntakeWhatsappRoute =
  ApiPublicHooksApIntakeWhatsappRouteImport.update({
    id: '/api/public/hooks/ap-intake-whatsapp',
    path: '/api/public/hooks/ap-intake-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApIntakeProcessRoute =
  ApiPublicHooksApIntakeProcessRouteImport.update({
    id: '/api/public/hooks/ap-intake-process',
    path: '/api/public/hooks/ap-intake-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApIntakeEmailRoute =
  ApiPublicHooksApIntakeEmailRouteImport.update({
    id: '/api/public/hooks/ap-intake-email',
    path: '/api/public/hooks/ap-intake-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify': typeof VerifyRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/reconciliation': typeof CashReconciliationRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/dashboard/cash-flow': typeof DashboardCashFlowRoute
  '/dashboard/profit-and-loss': typeof DashboardProfitAndLossRoute
  '/inbox-upload/$token': typeof InboxUploadTokenRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/ap-copilot': typeof PurchasesApCopilotRoute
  '/purchases/ap-dashboard': typeof PurchasesApDashboardRoute
  '/purchases/ap-review': typeof PurchasesApReviewRoute
  '/purchases/bills': typeof PurchasesBillsRouteWithChildren
  '/purchases/debit-notes': typeof PurchasesDebitNotesRouteWithChildren
  '/purchases/inbox': typeof PurchasesInboxRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRouteWithChildren
  '/purchases/scan': typeof PurchasesScanRoute
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/aged-payables': typeof ReportsAgedPayablesRoute
  '/reports/aged-receivables': typeof ReportsAgedReceivablesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof ReportsProfitAndLossRoute
  '/reports/purchases-by-supplier': typeof ReportsPurchasesBySupplierRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-item': typeof ReportsSalesByItemRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/reports/statement': typeof ReportsStatementRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/vat-return': typeof ReportsVatReturnRoute
  '/sales/credit-notes': typeof SalesCreditNotesRouteWithChildren
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/sales/quotations': typeof SalesQuotationsRouteWithChildren
  '/sales/recurring': typeof SalesRecurringRoute
  '/sales/statements': typeof SalesStatementsRoute
  '/settings/accounting-foundation': typeof SettingsAccountingFoundationRoute
  '/settings/ap-thresholds': typeof SettingsApThresholdsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/determinations': typeof SettingsDeterminationsRoute
  '/settings/finance-health': typeof SettingsFinanceHealthRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/test-data': typeof SettingsTestDataRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/debit-notes/$id': typeof PurchasesDebitNotesIdRoute
  '/purchases/debit-notes/new': typeof PurchasesDebitNotesNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills/': typeof PurchasesBillsIndexRoute
  '/purchases/debit-notes/': typeof PurchasesDebitNotesIndexRoute
  '/purchases/purchase-orders/': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes/': typeof SalesCreditNotesIndexRoute
  '/sales/invoices/': typeof SalesInvoicesIndexRoute
  '/sales/quotations/': typeof SalesQuotationsIndexRoute
  '/api/public/hooks/ap-intake-email': typeof ApiPublicHooksApIntakeEmailRoute
  '/api/public/hooks/ap-intake-process': typeof ApiPublicHooksApIntakeProcessRoute
  '/api/public/hooks/ap-intake-whatsapp': typeof ApiPublicHooksApIntakeWhatsappRoute
  '/api/public/hooks/finance-health': typeof ApiPublicHooksFinanceHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify': typeof VerifyRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/reconciliation': typeof CashReconciliationRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/dashboard/cash-flow': typeof DashboardCashFlowRoute
  '/dashboard/profit-and-loss': typeof DashboardProfitAndLossRoute
  '/inbox-upload/$token': typeof InboxUploadTokenRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/ap-copilot': typeof PurchasesApCopilotRoute
  '/purchases/ap-dashboard': typeof PurchasesApDashboardRoute
  '/purchases/ap-review': typeof PurchasesApReviewRoute
  '/purchases/inbox': typeof PurchasesInboxRoute
  '/purchases/scan': typeof PurchasesScanRoute
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/aged-payables': typeof ReportsAgedPayablesRoute
  '/reports/aged-receivables': typeof ReportsAgedReceivablesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof ReportsProfitAndLossRoute
  '/reports/purchases-by-supplier': typeof ReportsPurchasesBySupplierRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-item': typeof ReportsSalesByItemRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/reports/statement': typeof ReportsStatementRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/vat-return': typeof ReportsVatReturnRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/recurring': typeof SalesRecurringRoute
  '/sales/statements': typeof SalesStatementsRoute
  '/settings/accounting-foundation': typeof SettingsAccountingFoundationRoute
  '/settings/ap-thresholds': typeof SettingsApThresholdsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/determinations': typeof SettingsDeterminationsRoute
  '/settings/finance-health': typeof SettingsFinanceHealthRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/test-data': typeof SettingsTestDataRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/debit-notes/$id': typeof PurchasesDebitNotesIdRoute
  '/purchases/debit-notes/new': typeof PurchasesDebitNotesNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills': typeof PurchasesBillsIndexRoute
  '/purchases/debit-notes': typeof PurchasesDebitNotesIndexRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes': typeof SalesCreditNotesIndexRoute
  '/sales/invoices': typeof SalesInvoicesIndexRoute
  '/sales/quotations': typeof SalesQuotationsIndexRoute
  '/api/public/hooks/ap-intake-email': typeof ApiPublicHooksApIntakeEmailRoute
  '/api/public/hooks/ap-intake-process': typeof ApiPublicHooksApIntakeProcessRoute
  '/api/public/hooks/ap-intake-whatsapp': typeof ApiPublicHooksApIntakeWhatsappRoute
  '/api/public/hooks/finance-health': typeof ApiPublicHooksFinanceHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify': typeof VerifyRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/cash/banks': typeof CashBanksRoute
  '/cash/payments': typeof CashPaymentsRoute
  '/cash/receipts': typeof CashReceiptsRoute
  '/cash/reconciliation': typeof CashReconciliationRoute
  '/cash/transactions': typeof CashTransactionsRoute
  '/cash/transfers': typeof CashTransfersRoute
  '/dashboard/cash-flow': typeof DashboardCashFlowRoute
  '/dashboard/profit-and-loss': typeof DashboardProfitAndLossRoute
  '/inbox-upload/$token': typeof InboxUploadTokenRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/ap-copilot': typeof PurchasesApCopilotRoute
  '/purchases/ap-dashboard': typeof PurchasesApDashboardRoute
  '/purchases/ap-review': typeof PurchasesApReviewRoute
  '/purchases/bills': typeof PurchasesBillsRouteWithChildren
  '/purchases/debit-notes': typeof PurchasesDebitNotesRouteWithChildren
  '/purchases/inbox': typeof PurchasesInboxRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRouteWithChildren
  '/purchases/scan': typeof PurchasesScanRoute
  '/purchases/suppliers': typeof PurchasesSuppliersRoute
  '/reports/aged-payables': typeof ReportsAgedPayablesRoute
  '/reports/aged-receivables': typeof ReportsAgedReceivablesRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof ReportsProfitAndLossRoute
  '/reports/purchases-by-supplier': typeof ReportsPurchasesBySupplierRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-item': typeof ReportsSalesByItemRoute
  '/reports/sales-report': typeof ReportsSalesReportRoute
  '/reports/statement': typeof ReportsStatementRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/vat-return': typeof ReportsVatReturnRoute
  '/sales/credit-notes': typeof SalesCreditNotesRouteWithChildren
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/sales/quotations': typeof SalesQuotationsRouteWithChildren
  '/sales/recurring': typeof SalesRecurringRoute
  '/sales/statements': typeof SalesStatementsRoute
  '/settings/accounting-foundation': typeof SettingsAccountingFoundationRoute
  '/settings/ap-thresholds': typeof SettingsApThresholdsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/determinations': typeof SettingsDeterminationsRoute
  '/settings/finance-health': typeof SettingsFinanceHealthRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sales-reps': typeof SettingsSalesRepsRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/test-data': typeof SettingsTestDataRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/purchases/bills/$id': typeof PurchasesBillsIdRoute
  '/purchases/bills/new': typeof PurchasesBillsNewRoute
  '/purchases/debit-notes/$id': typeof PurchasesDebitNotesIdRoute
  '/purchases/debit-notes/new': typeof PurchasesDebitNotesNewRoute
  '/purchases/purchase-orders/$id': typeof PurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof PurchasesPurchaseOrdersNewRoute
  '/sales/credit-notes/$id': typeof SalesCreditNotesIdRoute
  '/sales/credit-notes/new': typeof SalesCreditNotesNewRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
  '/sales/invoices/new': typeof SalesInvoicesNewRoute
  '/sales/quotations/$id': typeof SalesQuotationsIdRoute
  '/sales/quotations/new': typeof SalesQuotationsNewRoute
  '/purchases/bills/': typeof PurchasesBillsIndexRoute
  '/purchases/debit-notes/': typeof PurchasesDebitNotesIndexRoute
  '/purchases/purchase-orders/': typeof PurchasesPurchaseOrdersIndexRoute
  '/sales/credit-notes/': typeof SalesCreditNotesIndexRoute
  '/sales/invoices/': typeof SalesInvoicesIndexRoute
  '/sales/quotations/': typeof SalesQuotationsIndexRoute
  '/api/public/hooks/ap-intake-email': typeof ApiPublicHooksApIntakeEmailRoute
  '/api/public/hooks/ap-intake-process': typeof ApiPublicHooksApIntakeProcessRoute
  '/api/public/hooks/ap-intake-whatsapp': typeof ApiPublicHooksApIntakeWhatsappRoute
  '/api/public/hooks/finance-health': typeof ApiPublicHooksFinanceHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/auth'
    | '/copilot'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/verify'
    | '/accounting/chart-of-accounts'
    | '/accounting/general-ledger'
    | '/accounting/journal-entries'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/reconciliation'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/dashboard/cash-flow'
    | '/dashboard/profit-and-loss'
    | '/inbox-upload/$token'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/ap-copilot'
    | '/purchases/ap-dashboard'
    | '/purchases/ap-review'
    | '/purchases/bills'
    | '/purchases/debit-notes'
    | '/purchases/inbox'
    | '/purchases/purchase-orders'
    | '/purchases/scan'
    | '/purchases/suppliers'
    | '/reports/aged-payables'
    | '/reports/aged-receivables'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/purchases-by-supplier'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-item'
    | '/reports/sales-report'
    | '/reports/statement'
    | '/reports/trial-balance'
    | '/reports/vat-return'
    | '/sales/credit-notes'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/quotations'
    | '/sales/recurring'
    | '/sales/statements'
    | '/settings/accounting-foundation'
    | '/settings/ap-thresholds'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/currencies'
    | '/settings/determinations'
    | '/settings/finance-health'
    | '/settings/import-export'
    | '/settings/integrations'
    | '/settings/numbering'
    | '/settings/organization'
    | '/settings/payment-methods'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/test-data'
    | '/settings/users'
    | '/settings/workflows'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/debit-notes/$id'
    | '/purchases/debit-notes/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills/'
    | '/purchases/debit-notes/'
    | '/purchases/purchase-orders/'
    | '/sales/credit-notes/'
    | '/sales/invoices/'
    | '/sales/quotations/'
    | '/api/public/hooks/ap-intake-email'
    | '/api/public/hooks/ap-intake-process'
    | '/api/public/hooks/ap-intake-whatsapp'
    | '/api/public/hooks/finance-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/auth'
    | '/copilot'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/verify'
    | '/accounting/chart-of-accounts'
    | '/accounting/general-ledger'
    | '/accounting/journal-entries'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/reconciliation'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/dashboard/cash-flow'
    | '/dashboard/profit-and-loss'
    | '/inbox-upload/$token'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/ap-copilot'
    | '/purchases/ap-dashboard'
    | '/purchases/ap-review'
    | '/purchases/inbox'
    | '/purchases/scan'
    | '/purchases/suppliers'
    | '/reports/aged-payables'
    | '/reports/aged-receivables'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/purchases-by-supplier'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-item'
    | '/reports/sales-report'
    | '/reports/statement'
    | '/reports/trial-balance'
    | '/reports/vat-return'
    | '/sales/customers'
    | '/sales/recurring'
    | '/sales/statements'
    | '/settings/accounting-foundation'
    | '/settings/ap-thresholds'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/currencies'
    | '/settings/determinations'
    | '/settings/finance-health'
    | '/settings/import-export'
    | '/settings/integrations'
    | '/settings/numbering'
    | '/settings/organization'
    | '/settings/payment-methods'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/test-data'
    | '/settings/users'
    | '/settings/workflows'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/debit-notes/$id'
    | '/purchases/debit-notes/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills'
    | '/purchases/debit-notes'
    | '/purchases/purchase-orders'
    | '/sales/credit-notes'
    | '/sales/invoices'
    | '/sales/quotations'
    | '/api/public/hooks/ap-intake-email'
    | '/api/public/hooks/ap-intake-process'
    | '/api/public/hooks/ap-intake-whatsapp'
    | '/api/public/hooks/finance-health'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/auth'
    | '/copilot'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/projects'
    | '/select-organization'
    | '/verify'
    | '/accounting/chart-of-accounts'
    | '/accounting/general-ledger'
    | '/accounting/journal-entries'
    | '/cash/banks'
    | '/cash/payments'
    | '/cash/receipts'
    | '/cash/reconciliation'
    | '/cash/transactions'
    | '/cash/transfers'
    | '/dashboard/cash-flow'
    | '/dashboard/profit-and-loss'
    | '/inbox-upload/$token'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/reports'
    | '/inventory/warehouses'
    | '/purchases/ap-copilot'
    | '/purchases/ap-dashboard'
    | '/purchases/ap-review'
    | '/purchases/bills'
    | '/purchases/debit-notes'
    | '/purchases/inbox'
    | '/purchases/purchase-orders'
    | '/purchases/scan'
    | '/purchases/suppliers'
    | '/reports/aged-payables'
    | '/reports/aged-receivables'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/purchases-by-supplier'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-item'
    | '/reports/sales-report'
    | '/reports/statement'
    | '/reports/trial-balance'
    | '/reports/vat-return'
    | '/sales/credit-notes'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/quotations'
    | '/sales/recurring'
    | '/sales/statements'
    | '/settings/accounting-foundation'
    | '/settings/ap-thresholds'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/branches'
    | '/settings/currencies'
    | '/settings/determinations'
    | '/settings/finance-health'
    | '/settings/import-export'
    | '/settings/integrations'
    | '/settings/numbering'
    | '/settings/organization'
    | '/settings/payment-methods'
    | '/settings/roles'
    | '/settings/sales-reps'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/test-data'
    | '/settings/users'
    | '/settings/workflows'
    | '/purchases/bills/$id'
    | '/purchases/bills/new'
    | '/purchases/debit-notes/$id'
    | '/purchases/debit-notes/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/sales/credit-notes/$id'
    | '/sales/credit-notes/new'
    | '/sales/invoices/$id'
    | '/sales/invoices/new'
    | '/sales/quotations/$id'
    | '/sales/quotations/new'
    | '/purchases/bills/'
    | '/purchases/debit-notes/'
    | '/purchases/purchase-orders/'
    | '/sales/credit-notes/'
    | '/sales/invoices/'
    | '/sales/quotations/'
    | '/api/public/hooks/ap-intake-email'
    | '/api/public/hooks/ap-intake-process'
    | '/api/public/hooks/ap-intake-whatsapp'
    | '/api/public/hooks/finance-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRouteWithChildren
  AuthRoute: typeof AuthRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  VerifyRoute: typeof VerifyRoute
  CashBanksRoute: typeof CashBanksRoute
  CashPaymentsRoute: typeof CashPaymentsRoute
  CashReceiptsRoute: typeof CashReceiptsRoute
  CashReconciliationRoute: typeof CashReconciliationRoute
  CashTransactionsRoute: typeof CashTransactionsRoute
  CashTransfersRoute: typeof CashTransfersRoute
  InboxUploadTokenRoute: typeof InboxUploadTokenRoute
  InventoryAdjustmentsRoute: typeof InventoryAdjustmentsRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryReportsRoute: typeof InventoryReportsRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  PurchasesApCopilotRoute: typeof PurchasesApCopilotRoute
  PurchasesApDashboardRoute: typeof PurchasesApDashboardRoute
  PurchasesApReviewRoute: typeof PurchasesApReviewRoute
  PurchasesBillsRoute: typeof PurchasesBillsRouteWithChildren
  PurchasesDebitNotesRoute: typeof PurchasesDebitNotesRouteWithChildren
  PurchasesInboxRoute: typeof PurchasesInboxRoute
  PurchasesPurchaseOrdersRoute: typeof PurchasesPurchaseOrdersRouteWithChildren
  PurchasesScanRoute: typeof PurchasesScanRoute
  PurchasesSuppliersRoute: typeof PurchasesSuppliersRoute
  ReportsAgedPayablesRoute: typeof ReportsAgedPayablesRoute
  ReportsAgedReceivablesRoute: typeof ReportsAgedReceivablesRoute
  ReportsBalanceSheetRoute: typeof ReportsBalanceSheetRoute
  ReportsProfitAndLossRoute: typeof ReportsProfitAndLossRoute
  ReportsPurchasesBySupplierRoute: typeof ReportsPurchasesBySupplierRoute
  ReportsSalesByCustomerRoute: typeof ReportsSalesByCustomerRoute
  ReportsSalesByItemRoute: typeof ReportsSalesByItemRoute
  ReportsSalesReportRoute: typeof ReportsSalesReportRoute
  ReportsStatementRoute: typeof ReportsStatementRoute
  ReportsTrialBalanceRoute: typeof ReportsTrialBalanceRoute
  ReportsVatReturnRoute: typeof ReportsVatReturnRoute
  SalesCreditNotesRoute: typeof SalesCreditNotesRouteWithChildren
  SalesCustomersRoute: typeof SalesCustomersRoute
  SalesInvoicesRoute: typeof SalesInvoicesRouteWithChildren
  SalesQuotationsRoute: typeof SalesQuotationsRouteWithChildren
  SalesRecurringRoute: typeof SalesRecurringRoute
  SalesStatementsRoute: typeof SalesStatementsRoute
  SettingsAccountingFoundationRoute: typeof SettingsAccountingFoundationRoute
  SettingsApThresholdsRoute: typeof SettingsApThresholdsRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsDeterminationsRoute: typeof SettingsDeterminationsRoute
  SettingsFinanceHealthRoute: typeof SettingsFinanceHealthRoute
  SettingsImportExportRoute: typeof SettingsImportExportRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNumberingRoute: typeof SettingsNumberingRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsPaymentMethodsRoute: typeof SettingsPaymentMethodsRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSalesRepsRoute: typeof SettingsSalesRepsRoute
  SettingsTaxesRoute: typeof SettingsTaxesRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsTestDataRoute: typeof SettingsTestDataRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWorkflowsRoute: typeof SettingsWorkflowsRoute
  ApiPublicHooksApIntakeEmailRoute: typeof ApiPublicHooksApIntakeEmailRoute
  ApiPublicHooksApIntakeProcessRoute: typeof ApiPublicHooksApIntakeProcessRoute
  ApiPublicHooksApIntakeWhatsappRoute: typeof ApiPublicHooksApIntakeWhatsappRoute
  ApiPublicHooksFinanceHealthRoute: typeof ApiPublicHooksFinanceHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workflows': {
      id: '/settings/workflows'
      path: '/settings/workflows'
      fullPath: '/settings/workflows'
      preLoaderRoute: typeof SettingsWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/test-data': {
      id: '/settings/test-data'
      path: '/settings/test-data'
      fullPath: '/settings/test-data'
      preLoaderRoute: typeof SettingsTestDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/taxes': {
      id: '/settings/taxes'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof SettingsTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales-reps': {
      id: '/settings/sales-reps'
      path: '/settings/sales-reps'
      fullPath: '/settings/sales-reps'
      preLoaderRoute: typeof SettingsSalesRepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payment-methods': {
      id: '/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof SettingsPaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/numbering': {
      id: '/settings/numbering'
      path: '/settings/numbering'
      fullPath: '/settings/numbering'
      preLoaderRoute: typeof SettingsNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/import-export': {
      id: '/settings/import-export'
      path: '/settings/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof SettingsImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/finance-health': {
      id: '/settings/finance-health'
      path: '/settings/finance-health'
      fullPath: '/settings/finance-health'
      preLoaderRoute: typeof SettingsFinanceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/determinations': {
      id: '/settings/determinations'
      path: '/settings/determinations'
      fullPath: '/settings/determinations'
      preLoaderRoute: typeof SettingsDeterminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ap-thresholds': {
      id: '/settings/ap-thresholds'
      path: '/settings/ap-thresholds'
      fullPath: '/settings/ap-thresholds'
      preLoaderRoute: typeof SettingsApThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/accounting-foundation': {
      id: '/settings/accounting-foundation'
      path: '/settings/accounting-foundation'
      fullPath: '/settings/accounting-foundation'
      preLoaderRoute: typeof SettingsAccountingFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/statements': {
      id: '/sales/statements'
      path: '/sales/statements'
      fullPath: '/sales/statements'
      preLoaderRoute: typeof SalesStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/recurring': {
      id: '/sales/recurring'
      path: '/sales/recurring'
      fullPath: '/sales/recurring'
      preLoaderRoute: typeof SalesRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices': {
      id: '/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/credit-notes': {
      id: '/sales/credit-notes'
      path: '/sales/credit-notes'
      fullPath: '/sales/credit-notes'
      preLoaderRoute: typeof SalesCreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/vat-return': {
      id: '/reports/vat-return'
      path: '/reports/vat-return'
      fullPath: '/reports/vat-return'
      preLoaderRoute: typeof ReportsVatReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/trial-balance': {
      id: '/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof ReportsTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/statement': {
      id: '/reports/statement'
      path: '/reports/statement'
      fullPath: '/reports/statement'
      preLoaderRoute: typeof ReportsStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales-report': {
      id: '/reports/sales-report'
      path: '/reports/sales-report'
      fullPath: '/reports/sales-report'
      preLoaderRoute: typeof ReportsSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales-by-item': {
      id: '/reports/sales-by-item'
      path: '/reports/sales-by-item'
      fullPath: '/reports/sales-by-item'
      preLoaderRoute: typeof ReportsSalesByItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales-by-customer': {
      id: '/reports/sales-by-customer'
      path: '/reports/sales-by-customer'
      fullPath: '/reports/sales-by-customer'
      preLoaderRoute: typeof ReportsSalesByCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/purchases-by-supplier': {
      id: '/reports/purchases-by-supplier'
      path: '/reports/purchases-by-supplier'
      fullPath: '/reports/purchases-by-supplier'
      preLoaderRoute: typeof ReportsPurchasesBySupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/profit-and-loss': {
      id: '/reports/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/reports/profit-and-loss'
      preLoaderRoute: typeof ReportsProfitAndLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/balance-sheet': {
      id: '/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof ReportsBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/aged-receivables': {
      id: '/reports/aged-receivables'
      path: '/reports/aged-receivables'
      fullPath: '/reports/aged-receivables'
      preLoaderRoute: typeof ReportsAgedReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/aged-payables': {
      id: '/reports/aged-payables'
      path: '/reports/aged-payables'
      fullPath: '/reports/aged-payables'
      preLoaderRoute: typeof ReportsAgedPayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/suppliers': {
      id: '/purchases/suppliers'
      path: '/purchases/suppliers'
      fullPath: '/purchases/suppliers'
      preLoaderRoute: typeof PurchasesSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/scan': {
      id: '/purchases/scan'
      path: '/purchases/scan'
      fullPath: '/purchases/scan'
      preLoaderRoute: typeof PurchasesScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/purchase-orders': {
      id: '/purchases/purchase-orders'
      path: '/purchases/purchase-orders'
      fullPath: '/purchases/purchase-orders'
      preLoaderRoute: typeof PurchasesPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/inbox': {
      id: '/purchases/inbox'
      path: '/purchases/inbox'
      fullPath: '/purchases/inbox'
      preLoaderRoute: typeof PurchasesInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/debit-notes': {
      id: '/purchases/debit-notes'
      path: '/purchases/debit-notes'
      fullPath: '/purchases/debit-notes'
      preLoaderRoute: typeof PurchasesDebitNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/bills': {
      id: '/purchases/bills'
      path: '/purchases/bills'
      fullPath: '/purchases/bills'
      preLoaderRoute: typeof PurchasesBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/ap-review': {
      id: '/purchases/ap-review'
      path: '/purchases/ap-review'
      fullPath: '/purchases/ap-review'
      preLoaderRoute: typeof PurchasesApReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/ap-dashboard': {
      id: '/purchases/ap-dashboard'
      path: '/purchases/ap-dashboard'
      fullPath: '/purchases/ap-dashboard'
      preLoaderRoute: typeof PurchasesApDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/ap-copilot': {
      id: '/purchases/ap-copilot'
      path: '/purchases/ap-copilot'
      fullPath: '/purchases/ap-copilot'
      preLoaderRoute: typeof PurchasesApCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/reports': {
      id: '/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof InventoryReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/adjustments': {
      id: '/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof InventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-upload/$token': {
      id: '/inbox-upload/$token'
      path: '/inbox-upload/$token'
      fullPath: '/inbox-upload/$token'
      preLoaderRoute: typeof InboxUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profit-and-loss': {
      id: '/dashboard/profit-and-loss'
      path: '/profit-and-loss'
      fullPath: '/dashboard/profit-and-loss'
      preLoaderRoute: typeof DashboardProfitAndLossRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cash-flow': {
      id: '/dashboard/cash-flow'
      path: '/cash-flow'
      fullPath: '/dashboard/cash-flow'
      preLoaderRoute: typeof DashboardCashFlowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cash/transfers': {
      id: '/cash/transfers'
      path: '/cash/transfers'
      fullPath: '/cash/transfers'
      preLoaderRoute: typeof CashTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/transactions': {
      id: '/cash/transactions'
      path: '/cash/transactions'
      fullPath: '/cash/transactions'
      preLoaderRoute: typeof CashTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/reconciliation': {
      id: '/cash/reconciliation'
      path: '/cash/reconciliation'
      fullPath: '/cash/reconciliation'
      preLoaderRoute: typeof CashReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/receipts': {
      id: '/cash/receipts'
      path: '/cash/receipts'
      fullPath: '/cash/receipts'
      preLoaderRoute: typeof CashReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/payments': {
      id: '/cash/payments'
      path: '/cash/payments'
      fullPath: '/cash/payments'
      preLoaderRoute: typeof CashPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/banks': {
      id: '/cash/banks'
      path: '/cash/banks'
      fullPath: '/cash/banks'
      preLoaderRoute: typeof CashBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/journal-entries': {
      id: '/accounting/journal-entries'
      path: '/journal-entries'
      fullPath: '/accounting/journal-entries'
      preLoaderRoute: typeof AccountingJournalEntriesRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/general-ledger': {
      id: '/accounting/general-ledger'
      path: '/general-ledger'
      fullPath: '/accounting/general-ledger'
      preLoaderRoute: typeof AccountingGeneralLedgerRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/chart-of-accounts': {
      id: '/accounting/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/accounting/chart-of-accounts'
      preLoaderRoute: typeof AccountingChartOfAccountsRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/sales/quotations/': {
      id: '/sales/quotations/'
      path: '/'
      fullPath: '/sales/quotations/'
      preLoaderRoute: typeof SalesQuotationsIndexRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/invoices/': {
      id: '/sales/invoices/'
      path: '/'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof SalesInvoicesIndexRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/credit-notes/': {
      id: '/sales/credit-notes/'
      path: '/'
      fullPath: '/sales/credit-notes/'
      preLoaderRoute: typeof SalesCreditNotesIndexRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/purchases/purchase-orders/': {
      id: '/purchases/purchase-orders/'
      path: '/'
      fullPath: '/purchases/purchase-orders/'
      preLoaderRoute: typeof PurchasesPurchaseOrdersIndexRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/debit-notes/': {
      id: '/purchases/debit-notes/'
      path: '/'
      fullPath: '/purchases/debit-notes/'
      preLoaderRoute: typeof PurchasesDebitNotesIndexRouteImport
      parentRoute: typeof PurchasesDebitNotesRoute
    }
    '/purchases/bills/': {
      id: '/purchases/bills/'
      path: '/'
      fullPath: '/purchases/bills/'
      preLoaderRoute: typeof PurchasesBillsIndexRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
    '/sales/quotations/new': {
      id: '/sales/quotations/new'
      path: '/new'
      fullPath: '/sales/quotations/new'
      preLoaderRoute: typeof SalesQuotationsNewRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/quotations/$id': {
      id: '/sales/quotations/$id'
      path: '/$id'
      fullPath: '/sales/quotations/$id'
      preLoaderRoute: typeof SalesQuotationsIdRouteImport
      parentRoute: typeof SalesQuotationsRoute
    }
    '/sales/invoices/new': {
      id: '/sales/invoices/new'
      path: '/new'
      fullPath: '/sales/invoices/new'
      preLoaderRoute: typeof SalesInvoicesNewRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/invoices/$id': {
      id: '/sales/invoices/$id'
      path: '/$id'
      fullPath: '/sales/invoices/$id'
      preLoaderRoute: typeof SalesInvoicesIdRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
    '/sales/credit-notes/new': {
      id: '/sales/credit-notes/new'
      path: '/new'
      fullPath: '/sales/credit-notes/new'
      preLoaderRoute: typeof SalesCreditNotesNewRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/sales/credit-notes/$id': {
      id: '/sales/credit-notes/$id'
      path: '/$id'
      fullPath: '/sales/credit-notes/$id'
      preLoaderRoute: typeof SalesCreditNotesIdRouteImport
      parentRoute: typeof SalesCreditNotesRoute
    }
    '/purchases/purchase-orders/new': {
      id: '/purchases/purchase-orders/new'
      path: '/new'
      fullPath: '/purchases/purchase-orders/new'
      preLoaderRoute: typeof PurchasesPurchaseOrdersNewRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/purchase-orders/$id': {
      id: '/purchases/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchases/purchase-orders/$id'
      preLoaderRoute: typeof PurchasesPurchaseOrdersIdRouteImport
      parentRoute: typeof PurchasesPurchaseOrdersRoute
    }
    '/purchases/debit-notes/new': {
      id: '/purchases/debit-notes/new'
      path: '/new'
      fullPath: '/purchases/debit-notes/new'
      preLoaderRoute: typeof PurchasesDebitNotesNewRouteImport
      parentRoute: typeof PurchasesDebitNotesRoute
    }
    '/purchases/debit-notes/$id': {
      id: '/purchases/debit-notes/$id'
      path: '/$id'
      fullPath: '/purchases/debit-notes/$id'
      preLoaderRoute: typeof PurchasesDebitNotesIdRouteImport
      parentRoute: typeof PurchasesDebitNotesRoute
    }
    '/purchases/bills/new': {
      id: '/purchases/bills/new'
      path: '/new'
      fullPath: '/purchases/bills/new'
      preLoaderRoute: typeof PurchasesBillsNewRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
    '/purchases/bills/$id': {
      id: '/purchases/bills/$id'
      path: '/$id'
      fullPath: '/purchases/bills/$id'
      preLoaderRoute: typeof PurchasesBillsIdRouteImport
      parentRoute: typeof PurchasesBillsRoute
    }
    '/api/public/hooks/finance-health': {
      id: '/api/public/hooks/finance-health'
      path: '/api/public/hooks/finance-health'
      fullPath: '/api/public/hooks/finance-health'
      preLoaderRoute: typeof ApiPublicHooksFinanceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ap-intake-whatsapp': {
      id: '/api/public/hooks/ap-intake-whatsapp'
      path: '/api/public/hooks/ap-intake-whatsapp'
      fullPath: '/api/public/hooks/ap-intake-whatsapp'
      preLoaderRoute: typeof ApiPublicHooksApIntakeWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ap-intake-process': {
      id: '/api/public/hooks/ap-intake-process'
      path: '/api/public/hooks/ap-intake-process'
      fullPath: '/api/public/hooks/ap-intake-process'
      preLoaderRoute: typeof ApiPublicHooksApIntakeProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ap-intake-email': {
      id: '/api/public/hooks/ap-intake-email'
      path: '/api/public/hooks/ap-intake-email'
      fullPath: '/api/public/hooks/ap-intake-email'
      preLoaderRoute: typeof ApiPublicHooksApIntakeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountingRouteChildren {
  AccountingChartOfAccountsRoute: typeof AccountingChartOfAccountsRoute
  AccountingGeneralLedgerRoute: typeof AccountingGeneralLedgerRoute
  AccountingJournalEntriesRoute: typeof AccountingJournalEntriesRoute
}

const AccountingRouteChildren: AccountingRouteChildren = {
  AccountingChartOfAccountsRoute: AccountingChartOfAccountsRoute,
  AccountingGeneralLedgerRoute: AccountingGeneralLedgerRoute,
  AccountingJournalEntriesRoute: AccountingJournalEntriesRoute,
}

const AccountingRouteWithChildren = AccountingRoute._addFileChildren(
  AccountingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCashFlowRoute: typeof DashboardCashFlowRoute
  DashboardProfitAndLossRoute: typeof DashboardProfitAndLossRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCashFlowRoute: DashboardCashFlowRoute,
  DashboardProfitAndLossRoute: DashboardProfitAndLossRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PurchasesBillsRouteChildren {
  PurchasesBillsIdRoute: typeof PurchasesBillsIdRoute
  PurchasesBillsNewRoute: typeof PurchasesBillsNewRoute
  PurchasesBillsIndexRoute: typeof PurchasesBillsIndexRoute
}

const PurchasesBillsRouteChildren: PurchasesBillsRouteChildren = {
  PurchasesBillsIdRoute: PurchasesBillsIdRoute,
  PurchasesBillsNewRoute: PurchasesBillsNewRoute,
  PurchasesBillsIndexRoute: PurchasesBillsIndexRoute,
}

const PurchasesBillsRouteWithChildren = PurchasesBillsRoute._addFileChildren(
  PurchasesBillsRouteChildren,
)

interface PurchasesDebitNotesRouteChildren {
  PurchasesDebitNotesIdRoute: typeof PurchasesDebitNotesIdRoute
  PurchasesDebitNotesNewRoute: typeof PurchasesDebitNotesNewRoute
  PurchasesDebitNotesIndexRoute: typeof PurchasesDebitNotesIndexRoute
}

const PurchasesDebitNotesRouteChildren: PurchasesDebitNotesRouteChildren = {
  PurchasesDebitNotesIdRoute: PurchasesDebitNotesIdRoute,
  PurchasesDebitNotesNewRoute: PurchasesDebitNotesNewRoute,
  PurchasesDebitNotesIndexRoute: PurchasesDebitNotesIndexRoute,
}

const PurchasesDebitNotesRouteWithChildren =
  PurchasesDebitNotesRoute._addFileChildren(PurchasesDebitNotesRouteChildren)

interface PurchasesPurchaseOrdersRouteChildren {
  PurchasesPurchaseOrdersIdRoute: typeof PurchasesPurchaseOrdersIdRoute
  PurchasesPurchaseOrdersNewRoute: typeof PurchasesPurchaseOrdersNewRoute
  PurchasesPurchaseOrdersIndexRoute: typeof PurchasesPurchaseOrdersIndexRoute
}

const PurchasesPurchaseOrdersRouteChildren: PurchasesPurchaseOrdersRouteChildren =
  {
    PurchasesPurchaseOrdersIdRoute: PurchasesPurchaseOrdersIdRoute,
    PurchasesPurchaseOrdersNewRoute: PurchasesPurchaseOrdersNewRoute,
    PurchasesPurchaseOrdersIndexRoute: PurchasesPurchaseOrdersIndexRoute,
  }

const PurchasesPurchaseOrdersRouteWithChildren =
  PurchasesPurchaseOrdersRoute._addFileChildren(
    PurchasesPurchaseOrdersRouteChildren,
  )

interface SalesCreditNotesRouteChildren {
  SalesCreditNotesIdRoute: typeof SalesCreditNotesIdRoute
  SalesCreditNotesNewRoute: typeof SalesCreditNotesNewRoute
  SalesCreditNotesIndexRoute: typeof SalesCreditNotesIndexRoute
}

const SalesCreditNotesRouteChildren: SalesCreditNotesRouteChildren = {
  SalesCreditNotesIdRoute: SalesCreditNotesIdRoute,
  SalesCreditNotesNewRoute: SalesCreditNotesNewRoute,
  SalesCreditNotesIndexRoute: SalesCreditNotesIndexRoute,
}

const SalesCreditNotesRouteWithChildren =
  SalesCreditNotesRoute._addFileChildren(SalesCreditNotesRouteChildren)

interface SalesInvoicesRouteChildren {
  SalesInvoicesIdRoute: typeof SalesInvoicesIdRoute
  SalesInvoicesNewRoute: typeof SalesInvoicesNewRoute
  SalesInvoicesIndexRoute: typeof SalesInvoicesIndexRoute
}

const SalesInvoicesRouteChildren: SalesInvoicesRouteChildren = {
  SalesInvoicesIdRoute: SalesInvoicesIdRoute,
  SalesInvoicesNewRoute: SalesInvoicesNewRoute,
  SalesInvoicesIndexRoute: SalesInvoicesIndexRoute,
}

const SalesInvoicesRouteWithChildren = SalesInvoicesRoute._addFileChildren(
  SalesInvoicesRouteChildren,
)

interface SalesQuotationsRouteChildren {
  SalesQuotationsIdRoute: typeof SalesQuotationsIdRoute
  SalesQuotationsNewRoute: typeof SalesQuotationsNewRoute
  SalesQuotationsIndexRoute: typeof SalesQuotationsIndexRoute
}

const SalesQuotationsRouteChildren: SalesQuotationsRouteChildren = {
  SalesQuotationsIdRoute: SalesQuotationsIdRoute,
  SalesQuotationsNewRoute: SalesQuotationsNewRoute,
  SalesQuotationsIndexRoute: SalesQuotationsIndexRoute,
}

const SalesQuotationsRouteWithChildren = SalesQuotationsRoute._addFileChildren(
  SalesQuotationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRouteWithChildren,
  AuthRoute: AuthRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  VerifyRoute: VerifyRoute,
  CashBanksRoute: CashBanksRoute,
  CashPaymentsRoute: CashPaymentsRoute,
  CashReceiptsRoute: CashReceiptsRoute,
  CashReconciliationRoute: CashReconciliationRoute,
  CashTransactionsRoute: CashTransactionsRoute,
  CashTransfersRoute: CashTransfersRoute,
  InboxUploadTokenRoute: InboxUploadTokenRoute,
  InventoryAdjustmentsRoute: InventoryAdjustmentsRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryReportsRoute: InventoryReportsRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  PurchasesApCopilotRoute: PurchasesApCopilotRoute,
  PurchasesApDashboardRoute: PurchasesApDashboardRoute,
  PurchasesApReviewRoute: PurchasesApReviewRoute,
  PurchasesBillsRoute: PurchasesBillsRouteWithChildren,
  PurchasesDebitNotesRoute: PurchasesDebitNotesRouteWithChildren,
  PurchasesInboxRoute: PurchasesInboxRoute,
  PurchasesPurchaseOrdersRoute: PurchasesPurchaseOrdersRouteWithChildren,
  PurchasesScanRoute: PurchasesScanRoute,
  PurchasesSuppliersRoute: PurchasesSuppliersRoute,
  ReportsAgedPayablesRoute: ReportsAgedPayablesRoute,
  ReportsAgedReceivablesRoute: ReportsAgedReceivablesRoute,
  ReportsBalanceSheetRoute: ReportsBalanceSheetRoute,
  ReportsProfitAndLossRoute: ReportsProfitAndLossRoute,
  ReportsPurchasesBySupplierRoute: ReportsPurchasesBySupplierRoute,
  ReportsSalesByCustomerRoute: ReportsSalesByCustomerRoute,
  ReportsSalesByItemRoute: ReportsSalesByItemRoute,
  ReportsSalesReportRoute: ReportsSalesReportRoute,
  ReportsStatementRoute: ReportsStatementRoute,
  ReportsTrialBalanceRoute: ReportsTrialBalanceRoute,
  ReportsVatReturnRoute: ReportsVatReturnRoute,
  SalesCreditNotesRoute: SalesCreditNotesRouteWithChildren,
  SalesCustomersRoute: SalesCustomersRoute,
  SalesInvoicesRoute: SalesInvoicesRouteWithChildren,
  SalesQuotationsRoute: SalesQuotationsRouteWithChildren,
  SalesRecurringRoute: SalesRecurringRoute,
  SalesStatementsRoute: SalesStatementsRoute,
  SettingsAccountingFoundationRoute: SettingsAccountingFoundationRoute,
  SettingsApThresholdsRoute: SettingsApThresholdsRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsDeterminationsRoute: SettingsDeterminationsRoute,
  SettingsFinanceHealthRoute: SettingsFinanceHealthRoute,
  SettingsImportExportRoute: SettingsImportExportRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNumberingRoute: SettingsNumberingRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsPaymentMethodsRoute: SettingsPaymentMethodsRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSalesRepsRoute: SettingsSalesRepsRoute,
  SettingsTaxesRoute: SettingsTaxesRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsTestDataRoute: SettingsTestDataRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWorkflowsRoute: SettingsWorkflowsRoute,
  ApiPublicHooksApIntakeEmailRoute: ApiPublicHooksApIntakeEmailRoute,
  ApiPublicHooksApIntakeProcessRoute: ApiPublicHooksApIntakeProcessRoute,
  ApiPublicHooksApIntakeWhatsappRoute: ApiPublicHooksApIntakeWhatsappRoute,
  ApiPublicHooksFinanceHealthRoute: ApiPublicHooksFinanceHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
